# Generated by Django 5.2.7 on 2025-10-21 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Feeding date'),
        ),
    ]
